exports.PLAY = 'PLAY';
exports.PLAY_DONE = 'PLAY_DONE';
exports.PLAY_ERROR = 'PLAY_ERROR';

exports.STOP = 'STOP';
exports.STOP_DONE = 'STOP_DONE';
exports.STOP_ERROR = 'STOP_ERROR';

exports.SHOW_MESSAGE = 'SHOW_MESSAGE';
exports.HIDE_MESSAGE = 'HIDE_MESSAGE';

exports.UPDATE_ALARM_SETTINGS = 'UPDATE_ALARM_SETTINGS';
exports.UPDATE_ALARM_SETTINGS_DONE = 'UPDATE_ALARM_SETTINGS_DONE';
exports.UPDATE_ALARM_SETTINGS_ERROR = 'UPDATE_ALARM_SETTINGS_ERROR';
