#!/bin/sh

# Set full path to bluethroat daemon
DAEMON="/opt/bluethroat/bin/bluethroatd"

# WARNING! Do not touch anything below this comment!

### BEGIN INIT INFO
# Provides: bluethroatd
# Required-Start: $network $remote_fs $local_fs
# Required-Stop: $network $remote_fs $local_fs
# Should-Start: mpd
# Should-Stop: mpd
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop bluethroatd
# Description: Controls a node process for bluethroat daemon (bluethroatd)
### END INIT INFO

# The PATH should be explicitly set because it does not contain common home of
# node (/usr/local/bin) on startup
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

. /lib/lsb/init-functions

start() {
    msg=$($DAEMON start)
    if [ $? -ne 0 ]
    then
        log_failure_msg $msg
        exit 1
    fi
    log_success_msg $msg
}

stop() {
    msg=$($DAEMON stop)
    if [ $? -ne 0 ]
    then
        log_failure_msg $msg
        exit 1
    fi
    log_success_msg $msg
}

status() {
    $DAEMON status
    if [ $? -ne 0 ]
    then
        exit 1
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
esac

exit 0
